type MsgInfo {
  mid: ID!
  tags: [Tag]
  reactions: [String]
}

type MsgInfoList {
  items: [MsgInfo]
}

type Mutation {
  addTag(mid: ID!, room: String!, name: String!): MsgInfo
  addReaction(mid: ID!, room: String!, emoji: String!): MsgInfo
  removeReaction(mid: ID!, room: String!, emoji: String!): MsgInfo
}

type Query {
  getMsgInfo(mid: ID!): MsgInfo
  listMsgInfos(mids: [ID!]): MsgInfoList
}

type Subscription {
  changedMsgInfo: MsgInfo
    @aws_subscribe(mutations: ["addTag","addReaction"])
}

type Tag {
  name: String!
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
